---
title: Just the Docs
description: A Jekyll theme for documentation
baseurl: ''
url: ''
permalink: pretty
exclude:
- node_modules/
- "*.gemspec"
- "*.gem"
- Gemfile
- Gemfile.lock
- package.json
- package-lock.json
- script/
- LICENSE.txt
- lib/
- bin/
- README.md
- Rakefile
search_enabled: true
search_tokenizer_separator: "/[\\s/]+/"
heading_anchors: true
aux_links:
  Just the Docs on GitHub:
  - "//github.com/pmarsceill/just-the-docs"
footer_content: Copyright &copy; 2017-2019 Patrick Marsceill. Distributed by an <a
  href="https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt">MIT license.</a>
color_scheme: nil
ga_tracking: UA-2709176-10
plugins:
- jekyll-seo-tag
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
